# Copyright m8mble 2021.
# SPDX-License-Identifier: BSL-1.0

name: gcc
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        std: [ 20 ]
        gcc: [ 10, 11 ]
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        exclude:
          - gcc: 10
            os: ubuntu-22.04
          - gcc: 11
            os: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - if: matrix.gcc == '11'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{matrix.gcc}}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        env:
          CXX: g++-${{matrix.gcc}}
        run:
          cmake
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_CXX_STANDARD=${{matrix.std}}
          -DCLEANTEST_WERROR=ON
          $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
